### Get All products
GET http://localhost:3000/products

### Create a product
POST http://localhost:3000/products
Content-Type: application/json

{
    "name":"Apple",
    "price":699
}

### Get product by id
GET http://localhost:3000/products/6174330af7478bc76deb5175

### Updating product by ids
PATCH http://localhost:3000/products/6174341a338e862bd1d22ad5
Content-Type: application/json

{
    "name":"Applesss ne tetsw"
}


### delete te product by id
DELETE http://localhost:3000/products/6174341a338e862bd1d22ad5

### error 404
GET http://localhost:3000/testr

###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name":"imacpro",
    "price":289900
}

###
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=imac&price=39384949